### ISSUE TITLE
How to change command palette font face ?

### ISSUE THREAD

**Issue by dandelionmood** [oivva/boxy-addon-font-face#1]
Hi,

thanks for your awesome work and especially for providing a way to set UI font : that's really something I was looking for ! I was wondering whether it was possible to customize the commande palette font as well, and how ?

Thanks for your help,
Pierre

**Comment by oivva** [comment]
@dandelionmood, hi!

Sorry it's not possible, you can't change neither size nor face of the command palette UI font. Maybe later if [this](https://forum.sublimetext.com/t/interface-suggestions/20828/6) will be implemented.

**Comment by dandelionmood** [comment]
Thanks for that kind answer @oivva ! 
Let's hope for the best then ;) !

**Comment by eproxus** [comment]
This can now be customized in Sublime Text 3 3127. See https://github.com/SublimeTextIssues/Core/issues/1314

It is documented here, under `quick_panel_label` and `quick_panel_path_label`: http://www.sublimetext.com/docs/3/themes.html

An example:

```json
  //
  // >> Command Palette
  // ===========================================================================
  {
    "class": "quick_panel_label",
    "font.face": "Iosevka"
  },
  {
    "class": "quick_panel_path_label",
    "font.face": "Iosevka"
  },
```
